"""`klix init` project generator.

This file is the only built-in end-user CLI shipped with the framework. Its
job is intentionally narrow: create a minimal working Klix app skeleton with a
valid package name, script entry point, and example command.
"""

import re
import sys
from pathlib import Path


# The generator accepts filesystem paths, but package metadata and script names
# still need a clean project identifier. This helper normalizes that boundary.
def sanitize_project_name(raw_name: str) -> str:
    name = Path(raw_name).name.strip()
    if not name:
        raise ValueError("Project name cannot be empty.")

    sanitized = re.sub(r"[^A-Za-z0-9._-]+", "-", name).strip(".-")
    if not sanitized:
        raise ValueError("Project name must contain at least one alphanumeric character.")
    return sanitized

PYPROJECT_TEMPLATE = """[project]
name = "{name}"
version = "0.1.0"
description = "A Klix tool"
requires-python = ">=3.9"
dependencies = [
    "klix"
]

[project.scripts]
{name} = "main:app.run"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["main"]
"""

MAIN_PY_TEMPLATE = """import klix
from pydantic import BaseModel
from dataclasses import dataclass

@dataclass
class AppState(klix.SessionState):
    counter: int = 0

class MyArgs(BaseModel):
    message: str

app = klix.App(
    name="{name}",
    version="0.1.0",
    description="Generated by klix init",
    state_schema=AppState
)

@app.on("start")
def on_start(session: klix.Session):
    session.ui.print("Welcome to {name}!", color="accent", bold=True)

@app.middleware
async def log(ctx: klix.MiddlewareContext, next: klix.NextFn):
    print(f"[Log] Incoming: {{ctx.raw_input}}")
    await next(ctx)

@app.command("/hello", help="Say hello", args_schema=MyArgs)
def hello(args: MyArgs, session: klix.Session):
    session.ui.print(f"{{args.message}}", color="success")
    session.state.counter += 1

if __name__ == "__main__":
    app.run()
"""

README_TEMPLATE = """# {name}

Generated with `klix init`.

## Development

```bash
pip install -e .
{name}
```
"""


# `main()` keeps the generator deliberately small: validate input, create the
# target directory, and write three starter files.
def main():
    if len(sys.argv) < 3 or sys.argv[1] != "init":
        print("Usage: klix init <name>")
        sys.exit(1)

    raw_name = sys.argv[2]
    path = Path(raw_name)

    try:
        name = sanitize_project_name(raw_name)
    except ValueError as exc:
        print(f"Error: {exc}")
        sys.exit(1)
    
    if path.exists():
        print(f"Error: Directory '{raw_name}' already exists.")
        sys.exit(1)

    path.mkdir(parents=True)
    
    (path / "pyproject.toml").write_text(PYPROJECT_TEMPLATE.format(name=name))
    (path / "main.py").write_text(MAIN_PY_TEMPLATE.format(name=name))
    (path / "README.md").write_text(README_TEMPLATE.format(name=name))

    print(f"Successfully initialized {path}!")
    print(f"Run 'cd {path} && pip install -e .' to get started.")

if __name__ == "__main__":
    main()
